apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-03-01T16:42:01Z
  labels:
    run: hw
  name: hw
  namespace: default
  resourceVersion: "389"
  selfLink: /api/v1/namespaces/default/services/hw
  uid: 778df34d-1d6f-11e8-8aa3-08002716e8d2
spec:
  clusterIP: 10.101.141.206
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32338
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: hw
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
